%YAML 1.2
---
learning_rate: 0.01
optim: SGD
batch_size: 1
nb_epoch: 1
n_layers: 20
hidden_num: 100
activation: relu 
loss_weight: ave
adaptive_weight: False
data: mb_sites
hedge: True
model: MLP
#momentum: 0.2
input_size: 28
log: log_hbp19
