%YAML 1.2
---
learning_rate: 0.01
optim: SGD
batch_size: 10
nb_epoch: 1 
n_layers: 4 
hidden_num: 100
activation: relu 
loss_weight: ave
adaptive_weight: False
data: higgs
hedge: False
model: MLP
input_size: 28
log: log_mlp4 
